import alsaaudio

print("CARDS: {}".format(alsaaudio.cards()))
print("MIXERS: {}".format(alsaaudio.mixers()))
pcms = alsaaudio.pcms(alsaaudio.PCM_CAPTURE)
print("PCM: {}".format(alsaaudio.PCM_CAPTURE))
print(pcms)
pcm = alsaaudio.PCM(alsaaudio.PCM_CAPTURE)
cap_mixer = alsaaudio.Mixer('Capture')
master_mixer = alsaaudio.Mixer('Master')
print(cap_mixer.volumecap())
print("CAPTURE RANGE: {}".format(cap_mixer.getrange(alsaaudio.PCM_CAPTURE)))
print(master_mixer.volumecap())
print("MASTER RANGE: {}".format(master_mixer.getrange(alsaaudio.PCM_PLAYBACK)))
cap_mixer.setvolume(100)
master_mixer.setvolume(100)
